# This is a basic workflow to help you get started with Actions

name: Github_workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
<<<<<<< HEAD
          with:
            version: 12
    - name: github action for yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install 
=======
        with:
          version: 12
          
      - name: github action for yarn
        uses: Borales/action-yarn@v2.1.0
        with:
            cmd: install 
>>>>>>> 74f4814534126ee1d87d44fe35b23697fe418ebe
        
      - name: Creating build
        run: yarn build
      # Runs a single command using the runners shell
      
      - name: installing surge  
        run: npm install -g surge
      
      - name: deploying on surge
        run: surge ./build http://bootcamp20_002.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
